/* AUTOGENERATED FILE - DO NOT EDIT CONTENTS */
/* This is a template file. Copy this to info.tsx and add your Supabase credentials */

export const projectId = "your-project-id-here"
export const publicAnonKey = "your-public-anon-key-here"
